export const data = {
  artwork: {
    categories: [
      "Paintings",
      "Sculptures",
      "Photography",
      "Digital Art",
      "Mixed Media",
      "Prints",
      "Drawings",
    ],
    filters: {
      Category: [
        "Abstract",
        "Portrait",
        "Landscape",
        "Still Life",
        "Contemporary",
        "Classical",
        "Modern",
      ],
      Style: [
        "Impressionism",
        "Cubism",
        "Surrealism",
        "Minimalism",
        "Pop Art",
        "Realism",
        "Expressionism",
      ],
      Medium: [
        "Oil on Canvas",
        "Acrylic",
        "Watercolor",
        "Charcoal",
        "Digital",
        "Bronze",
        "Marble",
      ],
    },
    featured: {
      title: "Featured Artwork",
      image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=1000",
    },
  },
  artists: {
    categories: [
      "Painters",
      "Sculptors",
      "Photographers",
      "Digital Artists",
      "Mixed Media Artists",
      "Printmakers",
    ],
    groups: {
      Emerging: [
        "Sofia Chen",
        "Marcus Rivera",
        "Elena Volkov",
        "James Park",
        "Aria Nakamura",
      ],
      Featured: [
        "Isabella Romano",
        "David Kim",
        "Sarah Mitchell",
        "Carlos Mendez",
        "Nina Petrov",
      ],
      Bestseller: [
        "Alexander Stone",
        "Maria Santos",
        "Robert Chen",
        "Lisa Anderson",
        "Ahmed Hassan",
      ],
      Famous: [
        "Catherine Moore",
        "Vincent Torres",
        "Rachel Green",
        "Michael Brown",
        "Anna Kowalski",
      ],
      Master: [
        "Leonardo Rossi",
        "Yuki Tanaka",
        "Pierre Dubois",
        "Sophia Williams",
        "Marco Benedetti",
      ],
    },
    profiles: [
      { name: "Isabella Romano", image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150" },
      { name: "Alexander Stone", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150" },
      { name: "Sofia Chen", image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=150" },
      { name: "Leonardo Rossi", image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150" },
      { name: "Catherine Moore", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150" },
      { name: "David Kim", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150" },
      { name: "Yuki Tanaka", image: "https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=150" },
      { name: "Maria Santos", image: "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&get=80&w=150" },
    ],
  },
  // pages: {
  //   "/": "Welcome to Zigguratss",
  //   "/artwork": "Artwork Collection",
  //   "/artist": "Artist Directory",
  //   "/exhibitions": "Exhibitions",
  //   "/about": "About Us",
  //   "/contact": "Contact",
  // },
};
