name: Deploy to VPS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch to deploy"
        required: true
        default: "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export PATH=$PATH:/opt/cpanel/ea-nodejs20/bin

            cd /home/***/www/app.zigguratss.com/zigguratss
            git fetch origin
            git checkout master
            git pull origin master
            npm install
            npm run build
            # sudo systemctl restart nginx
